name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: windows-latest
    name: CI
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - name: Setup premake
        uses: abel0b/setup-premake@v2
        with:
          version: "5.0.0-beta1"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Generate premake5 project
        run: premake5 vs2019
        shell: bash

      - name: Build 64bit release DLL
        run: |
          msbuild /p:Configuration=Release /p:Platform=x64 UND34D.sln -m /warnaserror

      - name: Check if DLL got built
        run: if (-Not (Test-Path -path "bin/Release/UND34D.dll")) {throw 1}

      - name: Rename DLL to UND34D-dev-{GITHUB_SHA}.dll
        run: ren UND34D.dll UND34D-dev-${{github.sha}}.dll
        working-directory: bin/Release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: |
            bin/Release/UND34D-dev-*.dll
